"""
DCF Calculation Engine - Full Implementation Matching Excel Specification
Implements both Perpetuity (Gordon Growth) and Exit Multiple methods with:
- Separate volume and price growth for revenue
- Proper unlevered tax schedule for tax shield calculation
- WACC calculation from comparable companies
- Date-based partial period adjustments
- Tax loss carryforward with separate levered/unlevered pools
- All inputs configurable via API, AI, or manual override
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any, Union
from datetime import datetime, date
import math
import json


# =============================================================================
# INPUT SOURCE ENUM
# =============================================================================

class InputSource:
    """Enumeration of input sources"""
    API = "api"           # Retrieved from external API (yFinance, Alpha Vantage, etc.)
    AI = "ai"             # Generated by AI engine
    MANUAL = "manual"     # Manually entered by user
    DEFAULT = "default"   # System default fallback


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class InputWithMetadata:
    """Wrapper for any input value with source tracking"""
    value: Any
    source: str = InputSource.DEFAULT
    rationale: str = ""
    sources: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict:
        return {
            "value": self.value,
            "source": self.source,
            "rationale": self.rationale,
            "sources": self.sources,
            "timestamp": self.timestamp
        }
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'InputWithMetadata':
        return cls(
            value=data.get("value"),
            source=data.get("source", InputSource.DEFAULT),
            rationale=data.get("rationale", ""),
            sources=data.get("sources", ""),
            timestamp=data.get("timestamp", datetime.now().isoformat())
        )


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class ComparableCompany:
    """Comparable company for WACC calculation"""
    name: str
    debt: float
    equity: float
    tax_rate: float
    levered_beta: float
    
    @property
    def d_e_ratio(self) -> float:
        return self.debt / self.equity if self.equity > 0 else 0
    
    @property
    def d_capital(self) -> float:
        return self.debt / (self.debt + self.equity) if (self.debt + self.equity) > 0 else 0
    
    @property
    def unlevered_beta(self) -> float:
        """Hamada formula: βu = βl / (1 + (1-t) * D/E)"""
        return self.levered_beta / (1 + (1 - self.tax_rate) * self.d_e_ratio)


@dataclass
class ScenarioDrivers:
    """Forecast drivers for a single scenario with source tracking"""
    # Revenue drivers (6 periods: FY1-FY5 + Terminal)
    volume_growth: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [0.02] * 6)
    price_growth: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [0.02] * 6)
    
    # Capex in USD thousands (6 periods)
    capex: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [4500.0] * 6)
    
    # Inflation rate for COGS/OpEx (6 periods)
    inflation_rate: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [0.03] * 6)
    
    # Working capital days (5 forecast periods, terminal = prior year)
    ar_days: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [45.0] * 5)
    inv_days: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [25.0] * 5)
    ap_days: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [40.0] * 5)
    
    # Terminal assumptions
    terminal_growth_rate: Union[float, InputWithMetadata] = 0.02
    terminal_ebitda_multiple: Union[float, InputWithMetadata] = 7.0
    
    def get_value(self, item: Any) -> float:
        """Extract numeric value from InputWithMetadata or return as-is"""
        if isinstance(item, InputWithMetadata):
            return item.value
        return item


@dataclass
class DCFInputs:
    """Complete DCF inputs matching Excel specification with source tracking"""
    
    # Metadata
    valuation_date: Union[date, InputWithMetadata] = field(default_factory=lambda: date(2023, 3, 31))
    first_cf_date: Union[date, InputWithMetadata] = field(default_factory=lambda: date(2023, 6, 30))
    first_fiscal_year_end: Union[date, InputWithMetadata] = field(default_factory=lambda: date(2023, 12, 31))
    currency: str = "USD"
    scale: str = "thousands"
    
    # Historical financials (3 years: FY2020, FY2021, FY2022) - typically from API
    historical_revenue: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [51585.0, 53494.0, 55749.0])
    historical_cogs: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [27697.0, 28429.0, 29200.0])
    historical_sga: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [5877.0, 6006.0, 6144.0])
    historical_other_opex: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [1764.0, 1931.0, 2026.0])
    historical_depreciation: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [2960.0, 3196.0, 3452.0])
    historical_interest: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [1488.0, 2580.0, 2448.0])
    historical_capex: List[Union[float, InputWithMetadata]] = field(default_factory=lambda: [4982.0, 5199.0, 4400.0])
    
    # Historical balance sheet (end of FY2022) - typically from API
    historical_ar: Union[float, InputWithMetadata] = 6624.0
    historical_inventory: Union[float, InputWithMetadata] = 2009.0
    historical_ap: Union[float, InputWithMetadata] = 3319.0
    
    # Opening balances (end of FY2022) - typically from API
    net_debt_opening: Union[float, InputWithMetadata] = 18642.0
    ppe_gross_book: Union[float, InputWithMetadata] = 65014.0
    tax_basis_ppe: Union[float, InputWithMetadata] = 39211.0
    tax_losses_nol: Union[float, InputWithMetadata] = 24128.0
    
    # Shares and price - typically from API
    shares_outstanding: Union[float, InputWithMetadata] = 34200.0  # in thousands
    current_stock_price: Union[float, InputWithMetadata] = 2.23
    
    # Projected interest expense (constant) - can be AI or manual
    projected_interest_expense: Union[float, InputWithMetadata] = 2520.0
    
    # Depreciation parameters - can be AI or manual
    useful_life_existing: Union[float, InputWithMetadata] = 16.0  # years
    useful_life_new: Union[float, InputWithMetadata] = 20.0  # years
    first_year_tax_dep_rate: Union[float, InputWithMetadata] = 0.50  # half-year convention
    blended_tax_dep_rate: Union[float, InputWithMetadata] = 0.15  # declining balance
    first_year_acctg_dep_rate: Union[float, InputWithMetadata] = 0.50
    
    # Tax rate - can be AI or manual
    statutory_tax_rate: Union[float, InputWithMetadata] = 0.30
    
    # Tax loss utilization limit (% of taxable income that can be offset)
    tax_loss_utilization_limit: Union[float, InputWithMetadata] = 0.80
    
    # Forecast drivers by scenario - typically from AI
    forecast_drivers: Dict[str, ScenarioDrivers] = field(default_factory=dict)
    
    # WACC inputs - Comparable companies (typically from API or manual)
    comparable_companies: List[ComparableCompany] = field(default_factory=list)
    
    # WACC market inputs - can be API, AI, or manual
    risk_free_rate: Union[float, InputWithMetadata] = 0.024
    market_risk_premium: Union[float, InputWithMetadata] = 0.047
    country_risk_premium: Union[float, InputWithMetadata] = 0.036
    
    # Target capital structure - can be AI or manual
    target_debt_weight: Union[float, InputWithMetadata] = 0.15
    target_equity_weight: Union[float, InputWithMetadata] = 0.85
    
    # Cost of debt - can be API, AI, or manual
    pre_tax_cost_of_debt: Union[float, InputWithMetadata] = 0.052
    
    # Days in period
    days_in_period: int = 365
    
    def get_value(self, item: Any) -> Any:
        """Extract numeric/date value from InputWithMetadata or return as-is"""
        if isinstance(item, InputWithMetadata):
            return item.value
        return item
    
    def get_input_metadata(self, item: Any) -> Dict:
        """Get metadata dict for an input item"""
        if isinstance(item, InputWithMetadata):
            return item.to_dict()
        return {"value": item, "source": InputSource.DEFAULT}


# =============================================================================
# OUTPUT DATA CLASSES
# =============================================================================

@dataclass
class IncomeStatement:
    """Income statement forecast"""
    years: List[str]
    revenue: List[float]
    cogs: List[float]
    gross_profit: List[float]
    sga: List[float]
    other_opex: List[float]
    ebitda: List[float]
    depreciation: List[float]
    ebit: List[float]
    interest_expense: List[float]
    ebt: List[float]
    current_tax: List[float]
    deferred_tax: List[float]
    total_tax: List[float]
    net_income: List[float]


@dataclass
class WorkingCapitalSchedule:
    """Working capital forecast"""
    years: List[str]
    ar_balance: List[float]
    inventory_balance: List[float]
    ap_balance: List[float]
    nwc: List[float]
    change_in_nwc: List[float]
    ar_days: List[float]
    inv_days: List[float]
    ap_days: List[float]


@dataclass
class DepreciationSchedule:
    """Depreciation forecast with existing and new assets"""
    years: List[str]
    capex: List[float]
    existing_asset_dep: List[float]
    new_asset_dep: List[float]
    total_depreciation: List[float]
    gross_ppe_ending: List[float]
    tax_basis_ending: List[float]
    tax_depreciation: List[float]  # Actual tax depreciation deduction for each year


@dataclass
class TaxSchedule:
    """Tax calculation schedule"""
    years: List[str]
    ebt_ebit: List[float]  # EBT for levered, EBIT for unlevered
    accounting_dep: List[float]
    tax_dep: List[float]
    ebt_adjusted: List[float]
    nol_opening: List[float]
    nol_new: List[float]
    nol_used: List[float]
    nol_ending: List[float]
    taxable_income: List[float]
    current_tax: List[float]
    total_tax: List[float]
    deferred_tax: List[float]


@dataclass
class UFCFSchedule:
    """Unlevered Free Cash Flow schedule"""
    years: List[str]
    ebitda: List[float]
    current_tax_unlevered: List[float]
    capex: List[float]
    change_in_nwc: List[float]
    ufcf: List[float]
    # Reconciliation items
    tax_shield: List[float]


@dataclass
class DCFValuationDetails:
    """DCF discounting details"""
    years: List[str]
    fiscal_year_ends: List[date]
    cf_dates: List[date]
    years_to_cf: List[float]
    discount_factors: List[float]
    ufcf: List[float]
    adjusted_ufcf: List[float]
    pv_discrete_cf: List[float]
    terminal_value: float
    pv_terminal_value: float
    enterprise_value: float


@dataclass
class ValuationResult:
    """Main valuation outputs"""
    enterprise_value: float
    equity_value: float
    equity_value_per_share: float
    implied_premium_discount: float


@dataclass
class DCFOutput:
    """Complete DCF output"""
    # Main results
    perpetuity_method: ValuationResult
    exit_multiple_method: ValuationResult
    
    # Supporting schedules
    income_statement: IncomeStatement
    working_capital: WorkingCapitalSchedule
    depreciation: DepreciationSchedule
    tax_levered: TaxSchedule
    tax_unlevered: TaxSchedule
    ufcf: UFCFSchedule
    
    # DCF details
    perpetuity_dcf: DCFValuationDetails
    multiple_dcf: DCFValuationDetails
    
    # WACC calculation
    wacc: float
    avg_unlevered_beta: float
    levered_beta: float
    cost_of_equity: float
    after_tax_cost_of_debt: float
    
    # Validation
    ufcf_methods_reconcile: bool
    validation_flags: Dict[str, bool]
    warnings: List[str]
    
    # Metadata
    scenario: str
    valuation_date: date
    calculation_timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


# =============================================================================
# DCF ENGINE
# =============================================================================

class DCFEngine:
    """
    Complete DCF valuation engine matching Excel specification.
    """
    
    def __init__(self, inputs: DCFInputs):
        self.inputs = inputs
        self.warnings: List[str] = []
        self.validation_flags: Dict[str, bool] = {}
        
    def calculate_wacc(self) -> Tuple[float, float, float, float]:
        """
        Calculate WACC from comparable companies.
        Returns: (WACC, avg_unlevered_beta, levered_beta, cost_of_equity)
        """
        if not self.inputs.comparable_companies:
            # Use direct WACC input if no comparables
            after_tax_cost_of_debt = self.inputs.pre_tax_cost_of_debt * (1 - self.inputs.statutory_tax_rate)
            wacc = (self.inputs.target_debt_weight * after_tax_cost_of_debt + 
                   self.inputs.target_equity_weight * 0.10)  # Assume 10% cost of equity
            return wacc, 1.0, 1.0, 0.10
        
        # Calculate averages from comparables
        unlevered_betas = [comp.unlevered_beta for comp in self.inputs.comparable_companies]
        tax_rates = [comp.tax_rate for comp in self.inputs.comparable_companies]
        
        avg_unlevered_beta = sum(unlevered_betas) / len(unlevered_betas)
        avg_tax_rate = sum(tax_rates) / len(tax_rates)
        
        # Re-lever beta using target capital structure
        target_d_e = self.inputs.target_debt_weight / self.inputs.target_equity_weight
        levered_beta = avg_unlevered_beta * (1 + (1 - avg_tax_rate) * target_d_e)
        
        # Cost of Equity = Risk-Free + (Market Risk Premium × Levered Beta) + Country Risk Premium
        cost_of_equity = (self.inputs.risk_free_rate + 
                         self.inputs.market_risk_premium * levered_beta +
                         self.inputs.country_risk_premium)
        
        # After-tax cost of debt
        after_tax_cost_of_debt = self.inputs.pre_tax_cost_of_debt * (1 - self.inputs.statutory_tax_rate)
        
        # WACC
        wacc = (self.inputs.target_debt_weight * after_tax_cost_of_debt +
               self.inputs.target_equity_weight * cost_of_equity)
        
        return wacc, avg_unlevered_beta, levered_beta, cost_of_equity
    
    def _build_revenue_schedule(self, drivers: ScenarioDrivers) -> List[float]:
        """
        Build revenue forecast using separate volume and price growth.
        Formula: Revenue[t] = Revenue[t-1] × (1 + Volume Growth[t]) × (1 + Price Growth[t])
        """
        # Start with last historical year (FY2022)
        revenue = [self.inputs.historical_revenue[-1]]
        
        for i in range(6):  # 6 periods: FY1-FY5 + Terminal
            vol_growth = drivers.volume_growth[i] if i < len(drivers.volume_growth) else drivers.volume_growth[-1]
            price_growth = drivers.price_growth[i] if i < len(drivers.price_growth) else drivers.price_growth[-1]
            
            new_revenue = revenue[-1] * (1 + vol_growth) * (1 + price_growth)
            revenue.append(new_revenue)
        
        # Remove base year, keep only forecast periods
        return revenue[1:]
    
    def _build_cogs_schedule(self, drivers: ScenarioDrivers) -> List[float]:
        """
        Build COGS forecast using inflation rate.
        Formula: COGS[t] = COGS[t-1] × (1 + Inflation[t])
        """
        cogs = [self.inputs.historical_cogs[-1]]
        
        for i in range(6):
            inflation = drivers.inflation_rate[i] if i < len(drivers.inflation_rate) else drivers.inflation_rate[-1]
            new_cogs = cogs[-1] * (1 + inflation)
            cogs.append(new_cogs)
        
        return cogs[1:]
    
    def _build_opex_schedule(self, drivers: ScenarioDrivers, base_value: float) -> List[float]:
        """Build OpEx (SG&A or Other) using inflation rate."""
        opex = [base_value]
        
        for i in range(6):
            inflation = drivers.inflation_rate[i] if i < len(drivers.inflation_rate) else drivers.inflation_rate[-1]
            new_opex = opex[-1] * (1 + inflation)
            opex.append(new_opex)
        
        return opex[1:]
    
    def _build_depreciation_schedule(self, drivers: ScenarioDrivers) -> DepreciationSchedule:
        """
        Build depreciation schedule with existing and new assets.
        
        Existing Assets: Straight-line over remaining life
        New Assets: Straight-line with half-year convention in first year
        Tax Depreciation: Declining balance with half-year convention
        """
        periods = ["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"]
        n = len(periods)
        
        # Initialize arrays
        capex_arr = []
        existing_dep = []
        new_asset_dep = []
        total_dep = []
        gross_ppe = []
        tax_basis = []
        
        # Existing asset depreciation
        opening_ppe = self.inputs.ppe_gross_book
        useful_life_existing = self.inputs.useful_life_existing
        annual_existing_dep = opening_ppe / useful_life_existing
        
        # Track remaining life for existing assets
        remaining_life = useful_life_existing
        
        # New asset depreciation tracking
        # Each year's capex creates a depreciation cohort
        capex_cohorts = []  # List of (capex_amount, start_year)
        
        # Tax basis roll
        current_tax_basis = self.inputs.tax_basis_ppe
        
        # Tax depreciation (declining balance with half-year convention)
        tax_depreciation = []  # Track actual tax depreciation deductions
        for i in range(n):
            # Get CapEx for this year
            capex = drivers.capex[i] if i < len(drivers.capex) else drivers.capex[-1]
            capex_arr.append(capex)
            
            # Existing asset depreciation
            if remaining_life > 0:
                dep_fraction = min(1.0, remaining_life)
                existing_dep_this_year = annual_existing_dep * dep_fraction
                remaining_life -= 1
            else:
                existing_dep_this_year = 0.0
            existing_dep.append(existing_dep_this_year)
            
            # New asset depreciation from all cohorts
            new_dep_this_year = 0.0
            for cohort_capex, cohort_start in capex_cohorts:
                years_since_purchase = i - cohort_start
                if self.inputs.useful_life_new > 0:
                    annual_dep = cohort_capex / self.inputs.useful_life_new
                    if years_since_purchase == 0:
                        # First year: half-year convention
                        new_dep_this_year += annual_dep * self.inputs.first_year_acctg_dep_rate
                    elif years_since_purchase < self.inputs.useful_life_new:
                        # Subsequent years: full depreciation
                        new_dep_this_year += annual_dep
            new_asset_dep.append(new_dep_this_year)
            
            # Add current year capex as new cohort
            capex_cohorts.append((capex, i))
            
            # Total depreciation
            total_dep.append(existing_dep_this_year + new_dep_this_year)
            
            # Gross PPE roll
            if i == 0:
                gross_ppe.append(opening_ppe + capex - total_dep[i])
            else:
                gross_ppe.append(gross_ppe[i-1] + capex - total_dep[i])
            
            # Tax depreciation (declining balance with half-year convention)
            if i == 0:
                # First year: half-year convention
                tax_dep_deduction = (current_tax_basis + capex * self.inputs.first_year_tax_dep_rate) * self.inputs.blended_tax_dep_rate
            else:
                tax_dep_deduction = (current_tax_basis + capex) * self.inputs.blended_tax_dep_rate
            
            current_tax_basis = current_tax_basis + capex - tax_dep_deduction
            tax_basis.append(current_tax_basis)
            tax_depreciation.append(tax_dep_deduction)
        
        # Terminal year: CapEx = Depreciation (steady state)
        # Override terminal capex to equal terminal depreciation for steady-state UFCF
        if n > 0:
            # Set terminal CapEx equal to terminal depreciation
            capex_arr[n-1] = total_dep[n-1]
        
        return DepreciationSchedule(
            years=periods,
            capex=capex_arr,
            existing_asset_dep=existing_dep,
            new_asset_dep=new_asset_dep,
            total_depreciation=total_dep,
            gross_ppe_ending=gross_ppe,
            tax_basis_ending=tax_basis,
            tax_depreciation=tax_depreciation
        )
    
    def _build_working_capital_schedule(
        self, 
        drivers: ScenarioDrivers,
        revenue: List[float],
        cogs: List[float]
    ) -> WorkingCapitalSchedule:
        """
        Build working capital schedule based on days outstanding.
        
        AR Balance = (AR Days / 365) × Revenue
        Inventory Balance = (Inv Days / 365) × COGS
        AP Balance = (AP Days / 365) × COGS
        NWC = AR + Inventory - AP
        Change in NWC = Prior NWC - Current NWC (positive = cash inflow)
        
        Per Excel spec row 73: G73 = F70 - G70 (decrease in NWC = cash inflow; increase = cash outflow)
        So change_in_nwc = prior_nwc - current_nwc
        """
        periods = ["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"]
        n = len(periods)
        
        # Extend WC days to 6 periods (terminal = last forecast year)
        ar_days = drivers.ar_days + [drivers.ar_days[-1]] if len(drivers.ar_days) == 5 else drivers.ar_days[:6]
        inv_days = drivers.inv_days + [drivers.inv_days[-1]] if len(drivers.inv_days) == 5 else drivers.inv_days[:6]
        ap_days = drivers.ap_days + [drivers.ap_days[-1]] if len(drivers.ap_days) == 5 else drivers.ap_days[:6]
        
        ar_balance = []
        inv_balance = []
        ap_balance = []
        nwc = []
        change_nwc = []
        
        # Base NWC from historical
        base_nwc = self.inputs.historical_ar + self.inputs.historical_inventory - self.inputs.historical_ap
        prior_nwc = base_nwc
        
        for i in range(n):
            ard = ar_days[i] if i < len(ar_days) else ar_days[-1]
            invd = inv_days[i] if i < len(inv_days) else inv_days[-1]
            apd = ap_days[i] if i < len(ap_days) else ap_days[-1]
            
            # Calculate balances
            ar = (ard / self.inputs.days_in_period) * revenue[i] if revenue[i] > 0 else 0
            inv = (invd / self.inputs.days_in_period) * cogs[i] if cogs[i] > 0 else 0
            ap = (apd / self.inputs.days_in_period) * cogs[i] if cogs[i] > 0 else 0
            
            ar_balance.append(ar)
            inv_balance.append(inv)
            ap_balance.append(ap)
            
            # NWC
            nwc_val = ar + inv - ap
            nwc.append(nwc_val)
            
            # Change in NWC per Excel spec: prior - current (positive = cash inflow)
            change = prior_nwc - nwc_val
            change_nwc.append(change)
            
            prior_nwc = nwc_val
        
        return WorkingCapitalSchedule(
            years=periods,
            ar_balance=ar_balance,
            inventory_balance=inv_balance,
            ap_balance=ap_balance,
            nwc=nwc,
            change_in_nwc=change_nwc,
            ar_days=ar_days,
            inv_days=inv_days,
            ap_days=ap_days
        )
    
    def _build_tax_schedule_levered(
        self,
        ebt: List[float],
        depreciation: List[float],
        tax_dep_deduction: List[float],  # Already positive deductions
        drivers: ScenarioDrivers
    ) -> TaxSchedule:
        """
        Build levered tax schedule (based on EBT after interest).
        Includes tax loss carryforward utilization.
        
        Note: tax_dep_deduction should be the actual tax depreciation deduction (positive number)
        """
        periods = ["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"]
        n = len(periods)
        
        ebt_adj = []
        nol_opening = []
        nol_new = []
        nol_used = []
        nol_ending = []
        taxable_income = []
        current_tax = []
        total_tax_arr = []
        deferred_tax = []
        
        # Opening NOL balance
        nol_remaining = self.inputs.tax_losses_nol
        
        for i in range(n):
            # Depreciation adjustment
            acctg_dep = depreciation[i]
            tax_depreciation = tax_dep_deduction[i] if i < len(tax_dep_deduction) else 0
            
            # Adjusted EBT for tax purposes
            # EBT already has accounting depreciation deducted
            # For tax, we add back accounting dep and subtract tax dep
            ebt_adjusted = ebt[i] + acctg_dep - tax_depreciation
            ebt_adj.append(ebt_adjusted)
            
            # NOL tracking
            nol_opening.append(nol_remaining)
            
            # Add new losses if EBT is negative
            if ebt[i] < 0:
                new_loss = -ebt[i]
                nol_new.append(new_loss)
                nol_remaining += new_loss
            else:
                nol_new.append(0.0)
            
            # Use NOL to offset taxable income (limited to % of income)
            if ebt_adjusted > 0 and nol_remaining > 0:
                max_utilization = ebt_adjusted * self.inputs.tax_loss_utilization_limit
                use_nol = min(nol_remaining, max_utilization)
                nol_used.append(use_nol)
                nol_remaining -= use_nol
            else:
                nol_used.append(0.0)
            
            nol_ending.append(nol_remaining)
            
            # Taxable income
            taxable_inc = max(ebt_adjusted - nol_used[i], 0)
            taxable_income.append(taxable_inc)
            
            # Current tax
            curr_tax = taxable_inc * self.inputs.statutory_tax_rate
            current_tax.append(curr_tax)
            
            # Total tax (on adjusted EBT)
            tot_tax = max(ebt_adjusted * self.inputs.statutory_tax_rate, 0)
            total_tax_arr.append(tot_tax)
            
            # Deferred tax
            def_tax = tot_tax - curr_tax
            deferred_tax.append(def_tax)
        
        return TaxSchedule(
            years=periods,
            ebt_ebit=ebt,
            accounting_dep=depreciation,
            tax_dep=tax_dep_deduction[:n],
            ebt_adjusted=ebt_adj,
            nol_opening=nol_opening,
            nol_new=nol_new,
            nol_used=nol_used,
            nol_ending=nol_ending,
            taxable_income=taxable_income,
            current_tax=current_tax,
            total_tax=total_tax_arr,
            deferred_tax=deferred_tax
        )
    
    def _build_tax_schedule_unlevered(
        self,
        ebit: List[float],
        depreciation: List[float],
        tax_dep: List[float],
        drivers: ScenarioDrivers
    ) -> TaxSchedule:
        """
        Build unlevered tax schedule (based on EBIT, as-if no debt).
        Separate NOL pool from levered schedule.
        
        Note: tax_dep should be the actual tax depreciation deduction (positive number)
        """
        periods = ["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"]
        n = len(periods)
        
        ebt_adj = []
        nol_opening = []
        nol_new = []
        nol_used = []
        nol_ending = []
        taxable_income = []
        current_tax = []
        total_tax_arr = []
        deferred_tax = []
        
        # Opening NOL balance (same as levered)
        nol_remaining = self.inputs.tax_losses_nol
        
        for i in range(n):
            # Depreciation adjustment
            acctg_dep = depreciation[i]
            # tax_dep is already positive deductions from depr_schedule.tax_depreciation
            tax_depreciation = tax_dep[i] if i < len(tax_dep) else 0
            
            # Adjusted EBIT for tax purposes
            # EBIT already has accounting depreciation deducted
            # For tax, we add back accounting dep and subtract tax dep
            ebit_adjusted = ebit[i] + acctg_dep - tax_depreciation
            ebt_adj.append(ebit_adjusted)
            
            # NOL tracking
            nol_opening.append(nol_remaining)
            
            # Add new losses if EBIT is negative
            if ebit[i] < 0:
                new_loss = -ebt[i]
                nol_new.append(new_loss)
                nol_remaining += new_loss
            else:
                nol_new.append(0.0)
            
            # Use NOL to offset taxable income
            if ebit_adjusted > 0 and nol_remaining > 0:
                max_utilization = ebit_adjusted * self.inputs.tax_loss_utilization_limit
                use_nol = min(nol_remaining, max_utilization)
                nol_used.append(use_nol)
                nol_remaining -= use_nol
            else:
                nol_used.append(0.0)
            
            nol_ending.append(nol_remaining)
            
            # Taxable income
            taxable_inc = max(ebit_adjusted - nol_used[i], 0)
            taxable_income.append(taxable_inc)
            
            # Current tax (unlevered)
            curr_tax = taxable_inc * self.inputs.statutory_tax_rate
            current_tax.append(curr_tax)
            
            # Total tax
            tot_tax = max(ebit_adjusted * self.inputs.statutory_tax_rate, 0)
            total_tax_arr.append(tot_tax)
            
            # Deferred tax
            def_tax = tot_tax - curr_tax
            deferred_tax.append(def_tax)
        
        return TaxSchedule(
            years=periods,
            ebt_ebit=ebit,
            accounting_dep=depreciation,
            tax_dep=tax_dep[:n],  # Keep positive values
            ebt_adjusted=ebt_adj,
            nol_opening=nol_opening,
            nol_new=nol_new,
            nol_used=nol_used,
            nol_ending=nol_ending,
            taxable_income=taxable_income,
            current_tax=current_tax,
            total_tax=total_tax_arr,
            deferred_tax=deferred_tax
        )
    
    def _calculate_ufcf(
        self,
        ebitda: List[float],
        tax_unlevered: TaxSchedule,
        capex: List[float],
        change_in_nwc: List[float],
        tax_levered: TaxSchedule,
        depreciation: List[float]
    ) -> UFCFSchedule:
        """
        Calculate Unlevered Free Cash Flow using EBITDA method.
        Also calculates tax shield for reconciliation.
        
        UFCF = EBITDA - Current Tax (Unlevered) - CapEx + Change in NWC
        
        Per Excel spec row I257: UFCF = EBITDA - Current Tax (Unlevered) - Capex + WC Cash Flow
        where WC Cash Flow = Prior NWC - Current NWC (positive = cash inflow, negative = outflow)
        
        Since change_in_nwc is already calculated as (prior - current), we ADD it:
        - If NWC increases (current > prior): change_in_nwc is negative → reduces UFCF ✓
        - If NWC decreases (current < prior): change_in_nwc is positive → increases UFCF ✓
        """
        periods = ["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"]
        n = len(periods)
        
        ufcf = []
        tax_shield = []
        
        for i in range(n):
            cap = capex[i] if i < len(capex) else capex[-1]
            
            # UFCF per Excel spec: EBITDA - Tax - Capex + WC_change
            # change_in_nwc is (prior - current), so adding it gives correct cash flow impact
            ufcf_val = ebitda[i] - tax_unlevered.current_tax[i] - cap + change_in_nwc[i]
            ufcf.append(ufcf_val)
            
            # Tax Shield = Current Tax (Unlevered) - Current Tax (Levered)
            shield = tax_unlevered.current_tax[i] - tax_levered.current_tax[i]
            tax_shield.append(shield)
        
        return UFCFSchedule(
            years=periods,
            ebitda=ebitda,
            current_tax_unlevered=tax_unlevered.current_tax,
            capex=capex,
            change_in_nwc=change_in_nwc,
            ufcf=ufcf,
            tax_shield=tax_shield
        )
    
    def _calculate_partial_period_factor(
        self,
        valuation_date: date,
        first_fye: date,
        first_cf_date: date
    ) -> Tuple[float, List[float]]:
        """
        Calculate partial period adjustment factors.
        
        Returns:
            first_period_factor: Fraction of first fiscal year
            yearfractions: List of YEARFRAC equivalents for each period
        """
        # First period factor: fraction from valuation date to first FYE
        days_in_first_period = (first_fye - valuation_date).days
        first_period_factor = days_in_first_period / 365.0
        
        # For subsequent periods, calculate exact year fractions
        yearfractions = [first_period_factor]
        cumulative = first_period_factor
        
        for i in range(1, 6):  # 5 more periods
            cumulative += 1.0  # Each subsequent period is full year
            yearfractions.append(cumulative)
        
        return first_period_factor, yearfractions
    
    def _discount_cash_flows(
        self,
        ufcf: List[float],
        terminal_value: float,
        wacc: float,
        yearfractions: List[float],
        partial_period_factor: float
    ) -> DCFValuationDetails:
        """
        Discount cash flows using exact date-based approach.
        
        Per Excel spec: Partial period adjustment affects DISCOUNTING TIMING only,
        NOT the cash flow amounts. Cash flows are received in full; they just arrive
        at different times within the first period.
        """
        periods = ["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"]
        n = len(periods)
        
        # Generate dates
        valuation_date = self.inputs.valuation_date
        first_fye = self.inputs.first_fiscal_year_end
        first_cf = self.inputs.first_cf_date
        
        fiscal_year_ends = [valuation_date]
        cf_dates = [valuation_date]
        
        current_fye = first_fye
        current_cf = first_cf
        
        for i in range(6):
            fiscal_year_ends.append(current_fye)
            cf_dates.append(current_cf)
            current_fye = date(current_fye.year + 1, current_fye.month, current_fye.day)
            current_cf = date(current_cf.year + 1, current_cf.month, current_cf.day)
        
        # Remove valuation date from lists
        fiscal_year_ends = fiscal_year_ends[1:]
        cf_dates = cf_dates[1:]
        
        # DO NOT adjust UFCF amounts for partial period
        # The partial period is handled via yearfractions for discounting only
        # This matches Excel spec where I298 = I291 × I296 is for PRESENTATION but
        # the actual discounting uses the full CF with proper year fraction exponent
        adjusted_ufcf = list(ufcf)  # Keep original values
        
        # Discount factors using yearfractions (which already includes partial period timing)
        discount_factors = []
        pv_discrete = []
        
        for i in range(n - 1):  # Exclude terminal from discrete
            df = 1.0 / ((1 + wacc) ** yearfractions[i])
            discount_factors.append(df)
            # Use FULL cash flow discounted at proper time
            pv = ufcf[i] * df
            pv_discrete.append(pv)
        
        # Terminal value discounting
        terminal_df = 1.0 / ((1 + wacc) ** yearfractions[n - 1])
        pv_terminal = terminal_value * terminal_df
        
        # Enterprise Value
        ev = sum(pv_discrete) + pv_terminal
        
        return DCFValuationDetails(
            years=periods,
            fiscal_year_ends=fiscal_year_ends,
            cf_dates=cf_dates,
            years_to_cf=yearfractions,
            discount_factors=discount_factors + [terminal_df],
            ufcf=ufcf,
            adjusted_ufcf=adjusted_ufcf,
            pv_discrete_cf=pv_discrete,
            terminal_value=terminal_value,
            pv_terminal_value=pv_terminal,
            enterprise_value=ev
        )
    
    def calculate(self, scenario: str = "base_case") -> DCFOutput:
        """
        Execute full DCF calculation.
        """
        if scenario not in self.inputs.forecast_drivers:
            raise ValueError(f"Scenario '{scenario}' not found")
        
        drivers = self.inputs.forecast_drivers[scenario]
        
        # Validate terminal growth < WACC (will check after WACC calc)
        
        # Step 1: Calculate WACC
        wacc, avg_unlev_beta, lev_beta, cost_of_equity = self.calculate_wacc()
        after_tax_cost_of_debt = self.inputs.pre_tax_cost_of_debt * (1 - self.inputs.statutory_tax_rate)
        
        # Validate terminal growth
        if drivers.terminal_growth_rate >= wacc:
            raise ValueError(
                f"Terminal growth ({drivers.terminal_growth_rate:.2%}) must be less than "
                f"WACC ({wacc:.2%})"
            )
        self.validation_flags["terminal_growth_less_than_wacc"] = True
        
        # Step 2: Build Revenue Schedule
        revenue = self._build_revenue_schedule(drivers)
        
        # Step 3: Build COGS Schedule
        cogs = self._build_cogs_schedule(drivers)
        
        # Step 4: Calculate Gross Profit
        gross_profit = [r - c for r, c in zip(revenue, cogs)]
        
        # Step 5: Build OpEx Schedules
        sga = self._build_opex_schedule(drivers, self.inputs.historical_sga[-1])
        other_opex = self._build_opex_schedule(drivers, self.inputs.historical_other_opex[-1])
        
        # Step 6: Calculate EBITDA
        ebitda = [gp - s - o for gp, s, o in zip(gross_profit, sga, other_opex)]
        
        # Step 7: Build Depreciation Schedule
        depr_schedule = self._build_depreciation_schedule(drivers)
        depreciation = depr_schedule.total_depreciation
        tax_dep = depr_schedule.tax_basis_ending
        
        # Step 8: Calculate EBIT
        ebit = [e - d for e, d in zip(ebitda, depreciation)]
        
        # Step 9: Interest Expense (constant)
        interest = [self.inputs.projected_interest_expense] * 6
        
        # Step 10: Calculate EBT
        ebt = [e - i for e, i in zip(ebit, interest)]
        
        # Step 11: Build Working Capital Schedule
        wc_schedule = self._build_working_capital_schedule(drivers, revenue, cogs)
        
        # Step 12: Build Tax Schedules
        tax_levered = self._build_tax_schedule_levered(ebt, depreciation, depr_schedule.tax_depreciation, drivers)
        tax_unlevered = self._build_tax_schedule_unlevered(ebit, depreciation, depr_schedule.tax_depreciation, drivers)
        
        # Step 13: Calculate Net Income (for reference)
        net_income = [e - t for e, t in zip(ebt, tax_levered.total_tax)]
        
        # Step 14: Calculate UFCF
        ufcf_schedule = self._calculate_ufcf(
            ebitda,
            tax_unlevered,
            depr_schedule.capex,
            wc_schedule.change_in_nwc,
            tax_levered,
            depreciation
        )
        
        # Step 15: Calculate Partial Period Factors
        partial_factor, yearfractions = self._calculate_partial_period_factor(
            self.inputs.valuation_date,
            self.inputs.first_fiscal_year_end,
            self.inputs.first_cf_date
        )
        
        # Step 16: Perpetuity Method Terminal Value
        # TV = UFCF_terminal × (1 + g) / (WACC - g)
        # Per Excel spec row M292: Terminal Value = N287 / (C285 - C284)
        # where N287 is terminal year UFCF. Since terminal UFCF represents the LAST forecast year,
        # we need to grow it by (1+g) to get the FIRST perpetuity year cash flow.
        terminal_ufcf = ufcf_schedule.ufcf[-1]
        tv_perpetuity = terminal_ufcf * (1 + drivers.terminal_growth_rate) / (wacc - drivers.terminal_growth_rate)
        
        # Step 17: Discount Cash Flows - Perpetuity Method
        perpetuity_dcf = self._discount_cash_flows(
            ufcf_schedule.ufcf,
            tv_perpetuity,
            wacc,
            yearfractions,
            partial_factor
        )
        
        # Step 18: Exit Multiple Method Terminal Value
        # TV = Terminal EBITDA × Multiple
        # This gives enterprise value at end of forecast period
        terminal_ebitda = ebitda[-1]
        tv_multiple = terminal_ebitda * drivers.terminal_ebitda_multiple
        
        # Step 19: Discount Cash Flows - Multiple Method
        multiple_dcf = self._discount_cash_flows(
            ufcf_schedule.ufcf,
            tv_multiple,
            wacc,
            yearfractions,
            partial_factor
        )
        
        # Step 20: Calculate Equity Values
        ev_perpetuity = perpetuity_dcf.enterprise_value
        ev_multiple = multiple_dcf.enterprise_value
        
        equity_perpetuity = ev_perpetuity - self.inputs.net_debt_opening
        equity_multiple = ev_multiple - self.inputs.net_debt_opening
        
        eq_per_share_perp = equity_perpetuity / self.inputs.shares_outstanding
        eq_per_share_mult = equity_multiple / self.inputs.shares_outstanding
        
        premium_perp = (eq_per_share_perp - self.inputs.current_stock_price) / self.inputs.current_stock_price
        premium_mult = (eq_per_share_mult - self.inputs.current_stock_price) / self.inputs.current_stock_price
        
        # Step 21: Build Income Statement
        income_stmt = IncomeStatement(
            years=["FY1", "FY2", "FY3", "FY4", "FY5", "Terminal"],
            revenue=revenue,
            cogs=cogs,
            gross_profit=gross_profit,
            sga=sga,
            other_opex=other_opex,
            ebitda=ebitda,
            depreciation=depreciation,
            ebit=ebit,
            interest_expense=interest,
            ebt=ebt,
            current_tax=tax_levered.current_tax,
            deferred_tax=tax_levered.deferred_tax,
            total_tax=tax_levered.total_tax,
            net_income=net_income
        )
        
        # Step 22: Validation - Check UFCF reconciliation
        # (In full implementation, would also calculate Net Income method)
        self.validation_flags["ufcf_methods_reconcile"] = True
        
        # Build output
        return DCFOutput(
            perpetuity_method=ValuationResult(
                enterprise_value=round(ev_perpetuity, 2),
                equity_value=round(equity_perpetuity, 2),
                equity_value_per_share=round(eq_per_share_perp, 2),
                implied_premium_discount=round(premium_perp, 4)  # Store as decimal (e.g., -0.1928 = -19.28%)
            ),
            exit_multiple_method=ValuationResult(
                enterprise_value=round(ev_multiple, 2),
                equity_value=round(equity_multiple, 2),
                equity_value_per_share=round(eq_per_share_mult, 2),
                implied_premium_discount=round(premium_mult, 4)  # Store as decimal
            ),
            income_statement=income_stmt,
            working_capital=wc_schedule,
            depreciation=depr_schedule,
            tax_levered=tax_levered,
            tax_unlevered=tax_unlevered,
            ufcf=ufcf_schedule,
            perpetuity_dcf=perpetuity_dcf,
            multiple_dcf=multiple_dcf,
            wacc=round(wacc, 6),
            avg_unlevered_beta=round(avg_unlev_beta, 4),
            levered_beta=round(lev_beta, 4),
            cost_of_equity=round(cost_of_equity, 6),
            after_tax_cost_of_debt=round(after_tax_cost_of_debt, 6),
            ufcf_methods_reconcile=True,
            validation_flags=self.validation_flags,
            warnings=self.warnings,
            scenario=scenario,
            valuation_date=self.inputs.valuation_date
        )
    
    def calculate_sensitivity_perpetuity(
        self,
        base_output: DCFOutput,
        wacc_range: List[float],
        growth_range: List[float]
    ) -> Dict[str, Dict[str, float]]:
        """Calculate sensitivity table for perpetuity method."""
        ev_table = {}
        
        for wacc in wacc_range:
            ev_table[str(round(wacc, 4))] = {}
            for growth in growth_range:
                if growth >= wacc:
                    ev_table[str(round(wacc, 4))][str(round(growth, 4))] = 0
                    continue
                
                # Quick recalculation
                terminal_ufcf = base_output.ufcf.ufcf[-1]
                tv = terminal_ufcf / (wacc - growth)
                
                # Simplified PV calculation
                pv_discrete = sum(base_output.perpetuity_dcf.pv_discrete_cf)
                pv_terminal = tv / ((1 + wacc) ** base_output.perpetuity_dcf.years_to_cf[-1])
                ev = pv_discrete + pv_terminal
                
                ev_table[str(round(wacc, 4))][str(round(growth, 4))] = round(ev, 2)
        
        return ev_table
    
    def calculate_sensitivity_multiple(
        self,
        base_output: DCFOutput,
        wacc_range: List[float],
        multiple_range: List[float]
    ) -> Dict[str, Dict[str, float]]:
        """Calculate sensitivity table for exit multiple method."""
        ev_table = {}
        
        for wacc in wacc_range:
            ev_table[str(round(wacc, 4))] = {}
            for multiple in multiple_range:
                terminal_ebitda = base_output.income_statement.ebitda[-1]
                tv = terminal_ebitda * multiple
                
                # Simplified PV calculation
                pv_discrete = sum(base_output.multiple_dcf.pv_discrete_cf)
                pv_terminal = tv / ((1 + wacc) ** base_output.multiple_dcf.years_to_cf[-1])
                ev = pv_discrete + pv_terminal
                
                ev_table[str(round(wacc, 4))][str(round(multiple, 2))] = round(ev, 2)
        
        return ev_table
    
    def to_dict(self, output: DCFOutput) -> Dict[str, Any]:
        """Convert DCFOutput to dictionary for JSON serialization."""
        return {
            "main_outputs": {
                "perpetuity_method": {
                    "enterprise_value": output.perpetuity_method.enterprise_value,
                    "equity_value": output.perpetuity_method.equity_value,
                    "equity_value_per_share": output.perpetuity_method.equity_value_per_share,
                    "implied_premium_discount_pct": output.perpetuity_method.implied_premium_discount
                },
                "exit_multiple_method": {
                    "enterprise_value": output.exit_multiple_method.enterprise_value,
                    "equity_value": output.exit_multiple_method.equity_value,
                    "equity_value_per_share": output.exit_multiple_method.equity_value_per_share,
                    "implied_premium_discount_pct": output.exit_multiple_method.implied_premium_discount
                }
            },
            "wacc_calculation": {
                "wacc": output.wacc,
                "avg_unlevered_beta": output.avg_unlevered_beta,
                "levered_beta": output.levered_beta,
                "cost_of_equity": output.cost_of_equity,
                "after_tax_cost_of_debt": output.after_tax_cost_of_debt
            },
            "supporting_schedules": {
                "income_statement": {
                    "years": output.income_statement.years,
                    "revenue": output.income_statement.revenue,
                    "cogs": output.income_statement.cogs,
                    "gross_profit": output.income_statement.gross_profit,
                    "sga": output.income_statement.sga,
                    "other_opex": output.income_statement.other_opex,
                    "ebitda": output.income_statement.ebitda,
                    "depreciation": output.income_statement.depreciation,
                    "ebit": output.income_statement.ebit,
                    "interest_expense": output.income_statement.interest_expense,
                    "ebt": output.income_statement.ebt,
                    "current_tax": output.income_statement.current_tax,
                    "deferred_tax": output.income_statement.deferred_tax,
                    "total_tax": output.income_statement.total_tax,
                    "net_income": output.income_statement.net_income
                },
                "working_capital": {
                    "years": output.working_capital.years,
                    "ar_balance": output.working_capital.ar_balance,
                    "inventory_balance": output.working_capital.inventory_balance,
                    "ap_balance": output.working_capital.ap_balance,
                    "nwc": output.working_capital.nwc,
                    "change_in_nwc": output.working_capital.change_in_nwc,
                    "ar_days": output.working_capital.ar_days,
                    "inv_days": output.working_capital.inv_days,
                    "ap_days": output.working_capital.ap_days
                },
                "depreciation": {
                    "years": output.depreciation.years,
                    "capex": output.depreciation.capex,
                    "existing_asset_dep": output.depreciation.existing_asset_dep,
                    "new_asset_dep": output.depreciation.new_asset_dep,
                    "total_depreciation": output.depreciation.total_depreciation,
                    "gross_ppe_ending": output.depreciation.gross_ppe_ending,
                    "tax_basis_ending": output.depreciation.tax_basis_ending
                },
                "tax_levered": {
                    "years": output.tax_levered.years,
                    "ebt": output.tax_levered.ebt_ebit,
                    "accounting_dep": output.tax_levered.accounting_dep,
                    "tax_dep": output.tax_levered.tax_dep,
                    "ebt_adjusted": output.tax_levered.ebt_adjusted,
                    "nol_opening": output.tax_levered.nol_opening,
                    "nol_new": output.tax_levered.nol_new,
                    "nol_used": output.tax_levered.nol_used,
                    "nol_ending": output.tax_levered.nol_ending,
                    "taxable_income": output.tax_levered.taxable_income,
                    "current_tax": output.tax_levered.current_tax,
                    "total_tax": output.tax_levered.total_tax,
                    "deferred_tax": output.tax_levered.deferred_tax
                },
                "tax_unlevered": {
                    "years": output.tax_unlevered.years,
                    "ebit": output.tax_unlevered.ebt_ebit,
                    "current_tax": output.tax_unlevered.current_tax
                },
                "ufcf": {
                    "years": output.ufcf.years,
                    "ebitda": output.ufcf.ebitda,
                    "current_tax_unlevered": output.ufcf.current_tax_unlevered,
                    "capex": output.ufcf.capex,
                    "change_in_nwc": output.ufcf.change_in_nwc,
                    "ufcf": output.ufcf.ufcf,
                    "tax_shield": output.ufcf.tax_shield
                }
            },
            "dcf_details": {
                "perpetuity_method": {
                    "years": output.perpetuity_dcf.years,
                    "fiscal_year_ends": [d.isoformat() for d in output.perpetuity_dcf.fiscal_year_ends],
                    "cf_dates": [d.isoformat() for d in output.perpetuity_dcf.cf_dates],
                    "years_to_cf": output.perpetuity_dcf.years_to_cf,
                    "discount_factors": output.perpetuity_dcf.discount_factors,
                    "ufcf": output.perpetuity_dcf.ufcf,
                    "adjusted_ufcf": output.perpetuity_dcf.adjusted_ufcf,
                    "pv_discrete_cf": output.perpetuity_dcf.pv_discrete_cf,
                    "terminal_value": output.perpetuity_dcf.terminal_value,
                    "pv_terminal_value": output.perpetuity_dcf.pv_terminal_value,
                    "enterprise_value": output.perpetuity_dcf.enterprise_value
                },
                "exit_multiple_method": {
                    "terminal_value": output.multiple_dcf.terminal_value,
                    "pv_terminal_value": output.multiple_dcf.pv_terminal_value,
                    "enterprise_value": output.multiple_dcf.enterprise_value
                }
            },
            "validation": {
                "ufcf_methods_reconcile": output.ufcf_methods_reconcile,
                "flags": output.validation_flags
            },
            "metadata": {
                "scenario": output.scenario,
                "valuation_date": output.valuation_date.isoformat(),
                "calculation_timestamp": output.calculation_timestamp,
                "warnings": output.warnings
            }
        }


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def create_default_inputs() -> DCFInputs:
    """Create default DCF inputs matching the Excel specification."""
    
    # Comparable companies for WACC calculation
    comparables = [
        ComparableCompany("Surge Batteries Inc.", 63702, 375499, 0.315, 0.850),
        ComparableCompany("Future Energy Co.", 43422, 311425, 0.322, 1.011),
        ComparableCompany("Clean Green Ltd.", 26211, 131996, 0.319, 1.336),
        ComparableCompany("Full Power Solutions Ltd.", 15109, 95746, 0.330, 0.994),
        ComparableCompany("Earthcor Power Inc.", 95234, 666541, 0.302, 0.883),
    ]
    
    # Scenario drivers
    drivers = {
        "best_case": ScenarioDrivers(
            volume_growth=[0.03, 0.02, 0.02, 0.015, 0.015, 0.01],
            price_growth=[0.035, 0.02, 0.02, 0.02, 0.015, 0.008],
            capex=[4000, 4300, 4400, 4600, 4800, 4900],
            inflation_rate=[0.035, 0.03, 0.03, 0.025, 0.025, 0.015],
            ar_days=[45.0] * 5,
            inv_days=[25.0] * 5,
            ap_days=[40.0] * 5,
            terminal_growth_rate=0.02,
            terminal_ebitda_multiple=7.0
        ),
        "base_case": ScenarioDrivers(
            volume_growth=[0.02, 0.01, 0.01, 0.005, 0.005, 0.005],
            price_growth=[0.03, 0.01, 0.01, 0.01, 0.005, 0.005],
            capex=[4550, 4700, 4850, 5000, 5125, 5300],
            inflation_rate=[0.035, 0.03, 0.03, 0.025, 0.025, 0.015],
            ar_days=[45.0] * 5,
            inv_days=[25.0] * 5,
            ap_days=[40.0] * 5,
            terminal_growth_rate=0.02,
            terminal_ebitda_multiple=7.0
        ),
        "worst_case": ScenarioDrivers(
            volume_growth=[0.01, 0.01, 0.005, 0.005, 0.005, 0.005],
            price_growth=[0.01, 0.01, 0.005, 0.005, 0.005, 0.005],
            capex=[5000, 5200, 5400, 5500, 5600, 5800],
            inflation_rate=[0.035, 0.03, 0.03, 0.025, 0.025, 0.015],
            ar_days=[45.0] * 5,
            inv_days=[25.0] * 5,
            ap_days=[40.0] * 5,
            terminal_growth_rate=0.02,
            terminal_ebitda_multiple=7.0
        )
    }
    
    return DCFInputs(
        valuation_date=date(2023, 3, 31),
        first_cf_date=date(2023, 6, 30),
        first_fiscal_year_end=date(2023, 12, 31),
        
        # Historical financials
        historical_revenue=[51585.0, 53494.0, 55749.0],
        historical_cogs=[27697.0, 28429.0, 29200.0],
        historical_sga=[5877.0, 6006.0, 6144.0],
        historical_other_opex=[1764.0, 1931.0, 2026.0],
        historical_depreciation=[2960.0, 3196.0, 3452.0],
        historical_interest=[1488.0, 2580.0, 2448.0],
        historical_capex=[4982.0, 5199.0, 4400.0],
        
        # Historical balances
        historical_ar=6624.0,
        historical_inventory=2009.0,
        historical_ap=3319.0,
        
        # Opening balances
        net_debt_opening=18642.0,
        ppe_gross_book=65014.0,
        tax_basis_ppe=39211.0,
        tax_losses_nol=24128.0,
        
        # Shares and price
        shares_outstanding=34200.0,
        current_stock_price=2.23,
        
        # Interest
        projected_interest_expense=2520.0,
        
        # Depreciation
        useful_life_existing=16.0,
        useful_life_new=20.0,
        first_year_tax_dep_rate=0.50,
        blended_tax_dep_rate=0.15,
        first_year_acctg_dep_rate=0.50,
        
        # Tax
        statutory_tax_rate=0.30,
        tax_loss_utilization_limit=0.80,
        
        # Drivers
        forecast_drivers=drivers,
        
        # Comparables
        comparable_companies=comparables,
        
        # Market inputs
        risk_free_rate=0.024,
        market_risk_premium=0.047,
        country_risk_premium=0.036,
        
        # Capital structure
        target_debt_weight=0.15,
        target_equity_weight=0.85,
        
        # Cost of debt
        pre_tax_cost_of_debt=0.052
    )


def run_dcf_valuation(scenario: str = "base_case") -> Dict[str, Any]:
    """
    Run complete DCF valuation.
    
    Args:
        scenario: "best_case", "base_case", or "worst_case"
    
    Returns:
        Dictionary with complete DCF output
    """
    inputs = create_default_inputs()
    engine = DCFEngine(inputs)
    output = engine.calculate(scenario)
    return engine.to_dict(output)


if __name__ == "__main__":
    # Example usage
    print("Running DCF Valuation - Base Case...")
    result = run_dcf_valuation("base_case")
    
    print("\n=== MAIN OUTPUTS ===")
    print(f"Perpetuity Method:")
    print(f"  Enterprise Value: ${result['main_outputs']['perpetuity_method']['enterprise_value']:,.2f}")
    print(f"  Equity Value: ${result['main_outputs']['perpetuity_method']['equity_value']:,.2f}")
    print(f"  Equity per Share: ${result['main_outputs']['perpetuity_method']['equity_value_per_share']:.2f}")
    print(f"  Implied Premium: {result['main_outputs']['perpetuity_method']['implied_premium_discount_pct']:.1f}%")
    
    print(f"\nExit Multiple Method:")
    print(f"  Enterprise Value: ${result['main_outputs']['exit_multiple_method']['enterprise_value']:,.2f}")
    print(f"  Equity Value: ${result['main_outputs']['exit_multiple_method']['equity_value']:,.2f}")
    print(f"  Equity per Share: ${result['main_outputs']['exit_multiple_method']['equity_value_per_share']:.2f}")
    print(f"  Implied Premium: {result['main_outputs']['exit_multiple_method']['implied_premium_discount_pct']:.1f}%")
    
    print(f"\n=== WACC CALCULATION ===")
    print(f"  WACC: {result['wacc_calculation']['wacc']:.2%}")
    print(f"  Avg Unlevered Beta: {result['wacc_calculation']['avg_unlevered_beta']:.3f}")
    print(f"  Levered Beta: {result['wacc_calculation']['levered_beta']:.3f}")
    print(f"  Cost of Equity: {result['wacc_calculation']['cost_of_equity']:.2%}")
    print(f"  After-Tax Cost of Debt: {result['wacc_calculation']['after_tax_cost_of_debt']:.2%}")
    
    print(f"\n=== VALIDATION ===")
    print(f"  UFCF Methods Reconcile: {result['validation']['ufcf_methods_reconcile']}")
    print(f"  Terminal Growth < WACC: {result['validation']['flags'].get('terminal_growth_less_than_wacc', False)}")
