"""
Generate OpenAPI Spec for Frontend Type Generation

This script exports the FastAPI OpenAPI specification to the frontend directory,
enabling automatic TypeScript type generation via openapi-typescript.

Usage:
    python scripts/generate_spec.py
    
This should be run:
1. Before frontend builds in CI/CD
2. As a pre-commit hook
3. Manually when backend schemas change
"""

import json
from pathlib import Path
import sys

# Add the backend app to the Python path
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.main import app  # Import your FastAPI app instance


def export_spec():
    """Export the OpenAPI schema to the frontend src/api directory."""
    
    # Path where your frontend configuration resides
    output_path = (
        Path(__file__).parent.parent.parent
        / "frontend"
        / "src"
        / "api"
        / "openapi.json"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Extract the OpenAPI blueprint generated by FastAPI
    openapi_schema = app.openapi()
    
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(openapi_schema, f, indent=2, ensure_ascii=False)
    
    print(f"✅ Successfully exported fresh OpenAPI schema to {output_path}")
    print(f"📊 Total endpoints: {sum(len(paths) for paths in openapi_schema.get('paths', {}).values())}")
    print(f"📦 Total schemas: {len(openapi_schema.get('components', {}).get('schemas', {}))}")
    
    return output_path


if __name__ == "__main__":
    export_spec()
