/**
 * Backend API Contracts - Auto-generated from FastAPI OpenAPI Schema
 * 
 * This file is AUTO-GENERATED by running: npm run api:sync
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * Source: /backend/app/api/schemas/unified_step_schemas.py
 * Generated via: openapi-typescript from openapi.json
 * 
 * To update:
 * 1. Make schema changes in backend Pydantic models
 * 2. Run: python backend/scripts/generate_spec.py
 * 3. Run: npm run api:sync
 * 4. Commit both openapi.json and this file together
 */

import type { paths, components } from './openapi';

// Re-export all schema types for convenient importing
export type { paths, components };

// Extract commonly used schema types
export type UnifiedStep1Request = components['schemas']['UnifiedStep1Request'];
export type UnifiedStep1Response = components['schemas']['UnifiedStep1Response'];
export type UnifiedStep2Request = components['schemas']['UnifiedStep2Request'];
export type UnifiedStep2Response = components['schemas']['UnifiedStep2Response'];
export type UnifiedStep3Request = components['schemas']['UnifiedStep3Request'];
export type UnifiedStep3Response = components['schemas']['UnifiedStep3Response'];
export type UnifiedStep4Request = components['schemas']['UnifiedStep4Request'];
export type UnifiedStep4Response = components['schemas']['UnifiedStep4Response'];
export type UnifiedStep5Request = components['schemas']['UnifiedStep5Request'];
export type UnifiedStep5Response = components['schemas']['UnifiedStep5Response'];
export type UnifiedStep6Request = components['schemas']['UnifiedStep6Request'];
export type UnifiedStep6Response = components['schemas']['UnifiedStep6Response'];
export type UnifiedStep7Request = components['schemas']['UnifiedStep7Request'];
export type UnifiedStep7Response = components['schemas']['UnifiedStep7Response'];
export type UnifiedStep8InitializeRequest = components['schemas']['UnifiedStep8InitializeRequest'];
export type UnifiedStep8InitializeResponse = components['schemas']['UnifiedStep8InitializeResponse'];
export type UnifiedStep8GenerateRequest = components['schemas']['UnifiedStep8GenerateRequest'];
export type UnifiedStep8GenerateResponse = components['schemas']['UnifiedStep8GenerateResponse'];
export type UnifiedStep9Request = components['schemas']['UnifiedStep9Request'];
export type UnifiedStep9Response = components['schemas']['UnifiedStep9Response'];
export type UnifiedStep10Request = components['schemas']['UnifiedStep10Request'];
export type UnifiedStep10Response = components['schemas']['UnifiedStep10Response'];
export type UnifiedStep10MultiRequest = components['schemas']['UnifiedStep10MultiRequest'];
export type UnifiedStep10MultiResponse = components['schemas']['UnifiedStep10MultiResponse'];

// Extract nested types
export type DataField = components['schemas']['DataField'];
export type DataStatus = components['schemas']['DataStatus'];
export type ValuationMethod = components['schemas']['ValuationMethod'];
export type MarketType = components['schemas']['MarketType'];
export type PeerCompany = components['schemas']['PeerCompany'];
export type MissingDataSummary = components['schemas']['MissingDataSummary'];
export type SearchCompanyResult = components['schemas']['SearchCompanyResult'];
export type CompanyOverview = components['schemas']['CompanyOverview'];
export type SessionInfo = components['schemas']['SessionInfo'];
export type ModelSelectionConfirmation = components['schemas']['ModelSelectionConfirmation'];
export type AssumptionCategory = components['schemas']['AssumptionCategory'];
export type HistoricalFinancials = components['schemas']['HistoricalFinancials'];
export type ForecastDrivers = components['schemas']['ForecastDrivers'];
export type DCFInputs = components['schemas']['DCFInputs'];
export type DuPontRatios = components['schemas']['DuPontRatios'];
export type CompsMultiples = components['schemas']['CompsMultiples'];
export type ValuationResult = components['schemas']['ValuationResult'];

// Path operation types for type-safe API client
export type Step1SearchPath = paths['/api/step-1-search']['post'];
export type Step2CreateSessionPath = paths['/api/step-2-create-session']['post'];
export type Step3SelectModelsPath = paths['/api/step-3-select-models']['post'];
export type Step4DiscoverPeersPath = paths['/api/step-4-discover-peers']['post'];
export type Step4SavePeersPath = paths['/api/step-4-save-peers']['post'];
export type Step5PrepareAssumptionsPath = paths['/api/step-5-prepare-assumptions']['post'];
export type Step6FetchApiDataPath = paths['/api/step-6-fetch-api-data']['post'];
export type Step7RetrieveHistoricalDataPath = paths['/api/step-7-retrieve-historical-data']['post'];
export type Step8InitializePath = paths['/api/step-8-initialize']['post'];
export type Step8GenerateAiSuggestionPath = paths['/api/step-8-generate-ai-suggestion']['post'];
export type Step9ConfirmAssumptionsPath = paths['/api/step-9-confirm-assumptions']['post'];
export type Step10ValuatePath = paths['/api/step-10-valuate']['post'];
export type Step10ValuateMultiPath = paths['/api/step-10-valuate-multi']['post'];

// Request/Response body types for each endpoint
export type Step1SearchBody = Step1SearchPath['requestBody']['content']['application/json'];
export type Step1SearchResponse = Step1SearchPath['responses'][200]['content']['application/json'];

export type Step2CreateSessionBody = Step2CreateSessionPath['requestBody']['content']['application/json'];
export type Step2CreateSessionResponse = Step2CreateSessionPath['responses'][200]['content']['application/json'];

export type Step3SelectModelsBody = Step3SelectModelsPath['requestBody']['content']['application/json'];
export type Step3SelectModelsResponse = Step3SelectModelsPath['responses'][200]['content']['application/json'];

export type Step4DiscoverPeersBody = Step4DiscoverPeersPath['requestBody']['content']['application/json'];
export type Step4DiscoverPeersResponse = Step4DiscoverPeersPath['responses'][200]['content']['application/json'];

export type Step4SavePeersBody = Step4SavePeersPath['requestBody']['content']['application/json'];
export type Step4SavePeersResponse = Step4SavePeersPath['responses'][200]['content']['application/json'];

export type Step5PrepareAssumptionsBody = Step5PrepareAssumptionsPath['requestBody']['content']['application/json'];
export type Step5PrepareAssumptionsResponse = Step5PrepareAssumptionsPath['responses'][200]['content']['application/json'];

export type Step6FetchApiDataBody = Step6FetchApiDataPath['requestBody']['content']['application/json'];
export type Step6FetchApiDataResponse = Step6FetchApiDataPath['responses'][200]['content']['application/json'];

export type Step7RetrieveHistoricalDataBody = Step7RetrieveHistoricalDataPath['requestBody']['content']['application/json'];
export type Step7RetrieveHistoricalDataResponse = Step7RetrieveHistoricalDataPath['responses'][200]['content']['application/json'];

export type Step8InitializeBody = Step8InitializePath['requestBody']['content']['application/json'];
export type Step8InitializeResponse = Step8InitializePath['responses'][200]['content']['application/json'];

export type Step8GenerateAiSuggestionBody = Step8GenerateAiSuggestionPath['requestBody']['content']['application/json'];
export type Step8GenerateAiSuggestionResponse = Step8GenerateAiSuggestionPath['responses'][200]['content']['application/json'];

export type Step9ConfirmAssumptionsBody = Step9ConfirmAssumptionsPath['requestBody']['content']['application/json'];
export type Step9ConfirmAssumptionsResponse = Step9ConfirmAssumptionsPath['responses'][200]['content']['application/json'];

export type Step10ValuateBody = Step10ValuatePath['requestBody']['content']['application/json'];
export type Step10ValuateResponse = Step10ValuatePath['responses'][200]['content']['application/json'];

export type Step10ValuateMultiBody = Step10ValuateMultiPath['requestBody']['content']['application/json'];
export type Step10ValuateMultiResponse = Step10ValuateMultiPath['responses'][200]['content']['application/json'];

// Enum value types (frozen constants for runtime use)
export const DATA_STATUS = {
  RETRIEVED: 'RETRIEVED' as const,
  CALCULATED: 'CALCULATED' as const,
  ESTIMATED: 'ESTIMATED' as const,
  MISSING: 'MISSING' as const,
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE' as const,
  CACHED: 'CACHED' as const,
} as const;

export const VALUATION_METHOD = {
  DCF: 'DCF' as const,
  DUPONT: 'DUPONT' as const,
  COMPS: 'COMPS' as const,
} as const;

export const MARKET_TYPE = {
  INTERNATIONAL: 'international' as const,
  VIETNAM: 'vietnam' as const,
} as const;

// Type guards for runtime validation
export function isDataStatus(value: string): value is DataStatus {
  return Object.values(DATA_STATUS).includes(value as any);
}

export function isValuationMethod(value: string): value is ValuationMethod {
  return Object.values(VALUATION_METHOD).includes(value as any);
}

export function isMarketType(value: string): value is MarketType {
  return Object.values(MARKET_TYPE).includes(value as any);
}
